enum TokenError {
  NO_ERROR,
  UNAUTHORIZED,
  BAD_INPUT,
  COMPTROLLER_REJECTION,
  COMPTROLLER_CALCULATION_ERROR,
  INTEREST_RATE_MODEL_ERROR,
  INVALID_ACCOUNT_PAIR,
  INVALID_CLOSE_AMOUNT_REQUESTED,
  INVALID_COLLATERAL_FACTOR,
  MATH_ERROR,
  MARKET_NOT_FRESH,
  MARKET_NOT_LISTED,
  TOKEN_INSUFFICIENT_ALLOWANCE,
  TOKEN_INSUFFICIENT_BALANCE,
  TOKEN_INSUFFICIENT_CASH,
  TOKEN_TRANSFER_IN_FAILED,
  TOKEN_TRANSFER_OUT_FAILED,
  TOKEN_MINT_REDEEM_NOT_ALLOWED,
}

enum TokenFailureInfo {
  ACCEPT_ADMIN_PENDING_ADMIN_CHECK,
  ACCRUE_INTEREST_ACCUMULATED_INTEREST_CALCULATION_FAILED,
  ACCRUE_INTEREST_BORROW_RATE_CALCULATION_FAILED,
  ACCRUE_INTEREST_NEW_BORROW_INDEX_CALCULATION_FAILED,
  ACCRUE_INTEREST_NEW_TOTAL_BORROWS_CALCULATION_FAILED,
  ACCRUE_INTEREST_NEW_TOTAL_RESERVES_CALCULATION_FAILED,
  ACCRUE_INTEREST_SIMPLE_INTEREST_FACTOR_CALCULATION_FAILED,
  BORROW_ACCUMULATED_BALANCE_CALCULATION_FAILED,
  BORROW_ACCRUE_INTEREST_FAILED,
  BORROW_CASH_NOT_AVAILABLE,
  BORROW_FRESHNESS_CHECK,
  BORROW_NEW_TOTAL_BALANCE_CALCULATION_FAILED,
  BORROW_NEW_ACCOUNT_BORROW_BALANCE_CALCULATION_FAILED,
  BORROW_MARKET_NOT_LISTED,
  BORROW_COMPTROLLER_REJECTION,
  LIQUIDATE_ACCRUE_BORROW_INTEREST_FAILED,
  LIQUIDATE_ACCRUE_COLLATERAL_INTEREST_FAILED,
  LIQUIDATE_COLLATERAL_FRESHNESS_CHECK,
  LIQUIDATE_COMPTROLLER_REJECTION,
  LIQUIDATE_COMPTROLLER_CALCULATE_AMOUNT_SEIZE_FAILED,
  LIQUIDATE_CLOSE_AMOUNT_IS_UINT_MAX,
  LIQUIDATE_CLOSE_AMOUNT_IS_ZERO,
  LIQUIDATE_FRESHNESS_CHECK,
  LIQUIDATE_LIQUIDATOR_IS_BORROWER,
  LIQUIDATE_REPAY_BORROW_FRESH_FAILED,
  LIQUIDATE_SEIZE_BALANCE_INCREMENT_FAILED,
  LIQUIDATE_SEIZE_BALANCE_DECREMENT_FAILED,
  LIQUIDATE_SEIZE_COMPTROLLER_REJECTION,
  LIQUIDATE_SEIZE_LIQUIDATOR_IS_BORROWER,
  LIQUIDATE_SEIZE_TOO_MUCH,
  MINT_ACCRUE_INTEREST_FAILED,
  MINT_COMPTROLLER_REJECTION,
  MINT_EXCHANGE_CALCULATION_FAILED,
  MINT_EXCHANGE_RATE_READ_FAILED,
  MINT_FRESHNESS_CHECK,
  MINT_NEW_ACCOUNT_BALANCE_CALCULATION_FAILED,
  MINT_NEW_TOTAL_SUPPLY_CALCULATION_FAILED,
  MINT_TRANSFER_IN_FAILED,
  MINT_TRANSFER_IN_NOT_POSSIBLE,
  REDEEM_ACCRUE_INTEREST_FAILED,
  REDEEM_COMPTROLLER_REJECTION,
  REDEEM_EXCHANGE_TOKENS_CALCULATION_FAILED,
  REDEEM_EXCHANGE_AMOUNT_CALCULATION_FAILED,
  REDEEM_EXCHANGE_RATE_READ_FAILED,
  REDEEM_FRESHNESS_CHECK,
  REDEEM_NEW_ACCOUNT_BALANCE_CALCULATION_FAILED,
  REDEEM_NEW_TOTAL_SUPPLY_CALCULATION_FAILED,
  REDEEM_TRANSFER_OUT_NOT_POSSIBLE,
  REDUCE_RESERVES_ACCRUE_INTEREST_FAILED,
  REDUCE_RESERVES_ADMIN_CHECK,
  REDUCE_RESERVES_CASH_NOT_AVAILABLE,
  REDUCE_RESERVES_FRESH_CHECK,
  REDUCE_RESERVES_VALIDATION,
  REPAY_BEHALF_ACCRUE_INTEREST_FAILED,
  REPAY_BORROW_ACCRUE_INTEREST_FAILED,
  REPAY_BORROW_ACCUMULATED_BALANCE_CALCULATION_FAILED,
  REPAY_BORROW_COMPTROLLER_REJECTION,
  REPAY_BORROW_FRESHNESS_CHECK,
  REPAY_BORROW_NEW_ACCOUNT_BORROW_BALANCE_CALCULATION_FAILED,
  REPAY_BORROW_NEW_TOTAL_BALANCE_CALCULATION_FAILED,
  REPAY_BORROW_TRANSFER_IN_NOT_POSSIBLE,
  SET_COLLATERAL_FACTOR_OWNER_CHECK,
  SET_COLLATERAL_FACTOR_VALIDATION,
  SET_COMPTROLLER_OWNER_CHECK,
  SET_INTEREST_RATE_MODEL_ACCRUE_INTEREST_FAILED,
  SET_INTEREST_RATE_MODEL_FRESH_CHECK,
  SET_INTEREST_RATE_MODEL_OWNER_CHECK,
  SET_MAX_ASSETS_OWNER_CHECK,
  SET_ORACLE_MARKET_NOT_LISTED,
  SET_PENDING_ADMIN_OWNER_CHECK,
  SET_RESERVE_FACTOR_ACCRUE_INTEREST_FAILED,
  SET_RESERVE_FACTOR_ADMIN_CHECK,
  SET_RESERVE_FACTOR_FRESH_CHECK,
  SET_RESERVE_FACTOR_BOUNDS_CHECK,
  TRANSFER_COMPTROLLER_REJECTION,
  TRANSFER_NOT_ALLOWED,
  TRANSFER_NOT_ENOUGH,
  TRANSFER_TOO_MUCH,
  ADD_RESERVES_ACCRUE_INTEREST_FAILED,
  ADD_RESERVES_FRESH_CHECK,
  ADD_RESERVES_TRANSFER_IN_NOT_POSSIBLE,
  REPAY_BEHALF_REQUIRE_EXPLICIT_AMOUNT,
  SET_MAX_TOTAL_SUPPLY_OWNER_CHECK,
}

const errorMessages: Record<number, string> = {
  [TokenError.NO_ERROR]: 'No error',
  [TokenError.UNAUTHORIZED]: 'Unauthorized',
  [TokenError.BAD_INPUT]: 'Bad input',
  [TokenError.COMPTROLLER_REJECTION]: '1swap Controller rejection',
  [TokenError.COMPTROLLER_CALCULATION_ERROR]: '1swap Controller calculation error',
  [TokenError.INTEREST_RATE_MODEL_ERROR]: 'Interest rate model error',
  [TokenError.INVALID_ACCOUNT_PAIR]: 'Invalid account pair',
  [TokenError.INVALID_CLOSE_AMOUNT_REQUESTED]: 'Invalid requested close amount',
  [TokenError.INVALID_COLLATERAL_FACTOR]: 'Invalid collateral factor',
  [TokenError.MATH_ERROR]: 'Math error',
  [TokenError.MARKET_NOT_FRESH]: 'Market not updated',
  [TokenError.MARKET_NOT_LISTED]: 'Market not listed',
  [TokenError.TOKEN_INSUFFICIENT_ALLOWANCE]: 'Insufficient allowance',
  [TokenError.TOKEN_INSUFFICIENT_BALANCE]: 'Insufficient balance',
  [TokenError.TOKEN_INSUFFICIENT_CASH]: 'Insufficient cash',
  [TokenError.TOKEN_TRANSFER_IN_FAILED]: 'Failed to transfer token in',
  [TokenError.TOKEN_TRANSFER_OUT_FAILED]: 'Failed to transfer token out',
  [TokenError.TOKEN_MINT_REDEEM_NOT_ALLOWED]: 'Failed to mint or redeem with token not allowed',
};

const failureMessages: Record<number, string> = {
  [TokenFailureInfo.ACCEPT_ADMIN_PENDING_ADMIN_CHECK]: 'Failed to accept admin role',
  [TokenFailureInfo.ACCRUE_INTEREST_ACCUMULATED_INTEREST_CALCULATION_FAILED]:
    'Failed to calculate accumulated interest',
  [TokenFailureInfo.ACCRUE_INTEREST_BORROW_RATE_CALCULATION_FAILED]:
    'Failed to calculate borrow rate ',
  [TokenFailureInfo.ACCRUE_INTEREST_NEW_BORROW_INDEX_CALCULATION_FAILED]:
    'Failed to calculate new borrow index',
  [TokenFailureInfo.ACCRUE_INTEREST_NEW_TOTAL_BORROWS_CALCULATION_FAILED]:
    'Failed to calculate new total borrows',
  [TokenFailureInfo.ACCRUE_INTEREST_NEW_TOTAL_RESERVES_CALCULATION_FAILED]:
    'Failed to calculate new total reserves',
  [TokenFailureInfo.ACCRUE_INTEREST_SIMPLE_INTEREST_FACTOR_CALCULATION_FAILED]:
    'Failed to calculate simple interest factor',
  [TokenFailureInfo.BORROW_ACCUMULATED_BALANCE_CALCULATION_FAILED]:
    'Failed to calculate borrow accumulated balance',
  [TokenFailureInfo.BORROW_ACCRUE_INTEREST_FAILED]: 'Failed to accrue interest for borrowing',
  [TokenFailureInfo.BORROW_CASH_NOT_AVAILABLE]: 'Borrow cash not available',
  [TokenFailureInfo.BORROW_FRESHNESS_CHECK]: 'Borrow freshness check',
  [TokenFailureInfo.BORROW_NEW_TOTAL_BALANCE_CALCULATION_FAILED]:
    'Failed to calculate new total balance calculation failed',
  [TokenFailureInfo.BORROW_NEW_ACCOUNT_BORROW_BALANCE_CALCULATION_FAILED]:
    'Failed to calculate new account borrow balance',
  [TokenFailureInfo.BORROW_MARKET_NOT_LISTED]: 'Borrow market not listed',
  [TokenFailureInfo.BORROW_COMPTROLLER_REJECTION]: 'Borrow 1swap controller rejection',
  [TokenFailureInfo.LIQUIDATE_ACCRUE_BORROW_INTEREST_FAILED]:
    'Liquidate accrue borrow interest failed',
  [TokenFailureInfo.LIQUIDATE_ACCRUE_COLLATERAL_INTEREST_FAILED]:
    'Liquidate accrue collateral interest failed',
  [TokenFailureInfo.LIQUIDATE_COLLATERAL_FRESHNESS_CHECK]:
    'Liquidate collateral freshness check',
  [TokenFailureInfo.LIQUIDATE_COMPTROLLER_REJECTION]: 'Liquidate comptroller rejection',
  [TokenFailureInfo.LIQUIDATE_COMPTROLLER_CALCULATE_AMOUNT_SEIZE_FAILED]:
    'Liquidate comptroller calculate amount seize failed',
  [TokenFailureInfo.LIQUIDATE_CLOSE_AMOUNT_IS_UINT_MAX]: 'Liquidate close amount is uint max',
  [TokenFailureInfo.LIQUIDATE_CLOSE_AMOUNT_IS_ZERO]: 'Liquidate close amount is zero',
  [TokenFailureInfo.LIQUIDATE_FRESHNESS_CHECK]: 'Liquidate freshness check',
  [TokenFailureInfo.LIQUIDATE_LIQUIDATOR_IS_BORROWER]: 'Liquidate liquidator is borrower',
  [TokenFailureInfo.LIQUIDATE_REPAY_BORROW_FRESH_FAILED]: 'Liquidate repay borrow fresh failed',
  [TokenFailureInfo.LIQUIDATE_SEIZE_BALANCE_INCREMENT_FAILED]:
    'Liquidate seize balance increment failed',
  [TokenFailureInfo.LIQUIDATE_SEIZE_BALANCE_DECREMENT_FAILED]:
    'Liquidate seize balance decrement failed',
  [TokenFailureInfo.LIQUIDATE_SEIZE_COMPTROLLER_REJECTION]:
    'Liquidate seize comptroller rejection',
  [TokenFailureInfo.LIQUIDATE_SEIZE_LIQUIDATOR_IS_BORROWER]:
    'Liquidate seize liquidator is borrower',
  [TokenFailureInfo.LIQUIDATE_SEIZE_TOO_MUCH]: 'Liquidate seize too much',
  [TokenFailureInfo.MINT_ACCRUE_INTEREST_FAILED]: 'Mint accrue interest failed',
  [TokenFailureInfo.MINT_COMPTROLLER_REJECTION]: 'Mint comptroller rejection',
  [TokenFailureInfo.MINT_EXCHANGE_CALCULATION_FAILED]: 'Mint exchange calculation failed',
  [TokenFailureInfo.MINT_EXCHANGE_RATE_READ_FAILED]: 'Mint exchange rate read failed',
  [TokenFailureInfo.MINT_FRESHNESS_CHECK]: 'Mint freshness check',
  [TokenFailureInfo.MINT_NEW_ACCOUNT_BALANCE_CALCULATION_FAILED]:
    'Mint new account balance calculation failed',
  [TokenFailureInfo.MINT_NEW_TOTAL_SUPPLY_CALCULATION_FAILED]:
    'Mint new total supply calculation failed',
  [TokenFailureInfo.MINT_TRANSFER_IN_FAILED]: 'Mint transfer in failed',
  [TokenFailureInfo.MINT_TRANSFER_IN_NOT_POSSIBLE]: 'Mint transfer in not possible',
  [TokenFailureInfo.REDEEM_ACCRUE_INTEREST_FAILED]: 'Redeem accrue interest failed',
  [TokenFailureInfo.REDEEM_COMPTROLLER_REJECTION]: 'Redeem comptroller rejection',
  [TokenFailureInfo.REDEEM_EXCHANGE_TOKENS_CALCULATION_FAILED]:
    'Redeem exchange tokens calculation failed',
  [TokenFailureInfo.REDEEM_EXCHANGE_AMOUNT_CALCULATION_FAILED]:
    'Redeem exchange amount calculation failed',
  [TokenFailureInfo.REDEEM_EXCHANGE_RATE_READ_FAILED]: 'Redeem exchange rate read failed',
  [TokenFailureInfo.REDEEM_FRESHNESS_CHECK]: 'Redeem freshness check',
  [TokenFailureInfo.REDEEM_NEW_ACCOUNT_BALANCE_CALCULATION_FAILED]:
    'Redeem new account balance calculation failed',
  [TokenFailureInfo.REDEEM_NEW_TOTAL_SUPPLY_CALCULATION_FAILED]:
    'Redeem new total supply calculation failed',
  [TokenFailureInfo.REDEEM_TRANSFER_OUT_NOT_POSSIBLE]: 'Redeem transfer out not possible',
  [TokenFailureInfo.REDUCE_RESERVES_ACCRUE_INTEREST_FAILED]:
    'Reduce reserves: accrue interest failed',
  [TokenFailureInfo.REDUCE_RESERVES_ADMIN_CHECK]: 'Reduce reserves admin check',
  [TokenFailureInfo.REDUCE_RESERVES_CASH_NOT_AVAILABLE]: 'Reduce reserves cash not available',
  [TokenFailureInfo.REDUCE_RESERVES_FRESH_CHECK]: 'Reduce reserves fresh check',
  [TokenFailureInfo.REDUCE_RESERVES_VALIDATION]: 'Reduce reserves validation',
  [TokenFailureInfo.REPAY_BEHALF_ACCRUE_INTEREST_FAILED]: 'Repay behalf accrue interest failed',
  [TokenFailureInfo.REPAY_BORROW_ACCRUE_INTEREST_FAILED]:
    'Repay borrow: accrue interest failed',
  [TokenFailureInfo.REPAY_BORROW_ACCUMULATED_BALANCE_CALCULATION_FAILED]:
    'Repay borrow: accumulated balance calculation failed',
  [TokenFailureInfo.REPAY_BORROW_COMPTROLLER_REJECTION]: 'Repay borrow: comptroller rejection',
  [TokenFailureInfo.REPAY_BORROW_FRESHNESS_CHECK]: 'Repay borrow: freshness check',
  [TokenFailureInfo.REPAY_BORROW_NEW_ACCOUNT_BORROW_BALANCE_CALCULATION_FAILED]:
    'Repay borrow: new account borrow balance calculation failed',
  [TokenFailureInfo.REPAY_BORROW_NEW_TOTAL_BALANCE_CALCULATION_FAILED]:
    'Repay borrow: new total balance calculation failed',
  [TokenFailureInfo.REPAY_BORROW_TRANSFER_IN_NOT_POSSIBLE]:
    'Repay borrow: transfer in not possible',
  [TokenFailureInfo.SET_COLLATERAL_FACTOR_OWNER_CHECK]: 'Set collateral factor owner check',
  [TokenFailureInfo.SET_COLLATERAL_FACTOR_VALIDATION]: 'Set collateral factor validation',
  [TokenFailureInfo.SET_COMPTROLLER_OWNER_CHECK]: 'Set comptroller owner check',
  [TokenFailureInfo.SET_INTEREST_RATE_MODEL_ACCRUE_INTEREST_FAILED]:
    'Set interest rate model accrue interest failed',
  [TokenFailureInfo.SET_INTEREST_RATE_MODEL_FRESH_CHECK]: 'Set interest rate model fresh check',
  [TokenFailureInfo.SET_INTEREST_RATE_MODEL_OWNER_CHECK]: 'Set interest rate model owner check',
  [TokenFailureInfo.SET_MAX_ASSETS_OWNER_CHECK]: 'Set max assets owner check',
  [TokenFailureInfo.SET_ORACLE_MARKET_NOT_LISTED]: 'Set oracle market not listed',
  [TokenFailureInfo.SET_PENDING_ADMIN_OWNER_CHECK]: 'Set pending admin owner check',
  [TokenFailureInfo.SET_RESERVE_FACTOR_ACCRUE_INTEREST_FAILED]:
    'Set reserve factor: accrue interest failed',
  [TokenFailureInfo.SET_RESERVE_FACTOR_ADMIN_CHECK]: 'Set reserve factor: admin check',
  [TokenFailureInfo.SET_RESERVE_FACTOR_FRESH_CHECK]: 'Set reserve factor: fresh check',
  [TokenFailureInfo.SET_RESERVE_FACTOR_BOUNDS_CHECK]: 'Set reserve factor: bounds check',
  [TokenFailureInfo.TRANSFER_COMPTROLLER_REJECTION]: 'Transfer comptroller rejection',
  [TokenFailureInfo.TRANSFER_NOT_ALLOWED]: 'Transfer not allowed',
  [TokenFailureInfo.TRANSFER_NOT_ENOUGH]: 'Transfer not enough',
  [TokenFailureInfo.TRANSFER_TOO_MUCH]: 'Transfer too much',
  [TokenFailureInfo.ADD_RESERVES_ACCRUE_INTEREST_FAILED]: 'Add reserves accrue interest failed',
  [TokenFailureInfo.ADD_RESERVES_FRESH_CHECK]: 'Add reserves fresh check',
  [TokenFailureInfo.ADD_RESERVES_TRANSFER_IN_NOT_POSSIBLE]:
    'Add reserves transfer in not possible',
  [TokenFailureInfo.REPAY_BEHALF_REQUIRE_EXPLICIT_AMOUNT]: 'Repay amount not valid',
  [TokenFailureInfo.SET_MAX_TOTAL_SUPPLY_OWNER_CHECK]: 'Only owner can set max supply',
};

export const parseTokenError = (error: number, info: number) => {
  return {
    error: errorMessages[error],
    info: failureMessages[info],
  };
};
